[package]
name = "contribute"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
path = "src/contribute.rs"

[dependencies.elrond-wasm]
version = "0.36.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.36.0"
